name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:

  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4

  # إضافة الواقع المعزز
#  ar_flutter_plugin: ^0.6.3
#  ar_flutter_plugin:
#    git:
#      url: https://github.com/CariusLars/ar_flutter_plugin.git
#      ref: v0.7.3
#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
    - assets/fonts/   # <--- تمت إضافتها

  fonts:
    - family: OldSouthArabian
      fonts:
        - asset: assets/fonts/NotoSansOldSouthArabian-Regular.ttf
